version: "3.9"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: G7b3$jPw#
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: G7b3$jPw#
      MYSQL_PORT: 3306
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_USER=myuser
      - DB_PASS=G7b3$jPw#
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_PORT=3306

volumes:
  db_data: {}
